[package]
name = "encrypt_with_chunks"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chacha20poly1305 = "0.10.1"
rpassword = "7.2.0"
sha3 = "0.10.7"
